### ISSUE TITLE
Typo in DataGenerator for case 4

### ISSUE THREAD

**Issue by xerxesr** [jwyyy/AdaFNN#2]
Thanks for publishing this, nice paper and code! In line https://github.com/jwyyy/AdaFNN/blame/master/AdaFNN.ipynb#L444 it should be
```
for i in range(n):
                Y[i, 0] = self._inner_product(beta2, X[i, :], h) + self._inner_product(beta1, X[i, :], h) ** 2
```
instead of
```
for i in range(n):
                Y[i, 0] = self._inner_product(beta2, X[i, :], h) + _inner_product(beta1, X[i, :], h) ** 2
```

**Comment by jwyyy** [comment]
@xerxesr Thanks for catching the typo! Although `self` is missing, two inner product operations are effectively the same. I will update the code soon. Thanks again!
